SELECT array_count(ARRAY['de','de','us']);
SELECT array_count(ARRAY[1,5,9,5,10,5,5]);
SELECT hstore_add('a=>1,b=>2'::hstore,'b=>1,c=>2'::inthstore);
SELECT hstore_add('a=>1,b=>1000000000'::hstore,'b=>1,c=>2'::inthstore);
SELECT hstore_add('a=>1.3,b=>2.5'::hstore,'b=>1.2,c=>2.4'::floathstore);
SELECT hstore_add('a=>1,b=>2'::hstore,'b=>1,c=>2'::inthstore);
SELECT hstore_sub('a=>2,b=>3'::hstore,'b=>1,c=>2'::inthstore);
SELECT array_count(ARRAY[NULL,5,NULL,5,10,NULL,5]);
SELECT array_count(ARRAY[-5,3,5]);
SELECT array_add(array_agg((num/30)::text), array_agg(val)) FROM generate_series(0,100) num, generate_series(0,1000,10) val;
SELECT SUM(hstore((num/30)::text, val::text)::inthstore) FROM generate_series(0,100) num, generate_series(0,1000,10) val;
SELECT array_add(ARRAY['foo','bar'],ARRAY[1,2,3]);
SELECT array_add(ARRAY['foo','bar','baz'],ARRAY[1,2]);
SELECT array_add(ARRAY['foo','foo','bar','foo'],ARRAY[2,NULL,2,2]);
SELECT array_add(ARRAY['foo',NULL,'foo','bar'],ARRAY[2,2,2,2]);
SELECT array_add(ARRAY['foo','bar','foo'],ARRAY[2E9::integer,2E9::integer,,2E9::integer]);